#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Usage:
    tree-list-completer [options] <path>

Options:
    -h, --help      Show this screen and exit.
    -v, --verbose   Show verbose output.
    --version       Show version.
"""

import csv
import docopt

def load_tree_list(path):
    tree_list = []
    with open(path, mode='r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            tree_list.append(row)
    return tree_list

if __name__ == '__main__':
    args = docopt.docopt(__doc__, version='0.1.0')
    tree_list = load_tree_list(args['<path>'])
    for tree in [t for t in tree_list if len(t['Botanical name']) == 0]:
        print(tree['Name'])
    
